

commandDictLower = {
 1:'a'.encode('utf-8'),
 2:'b'.encode('utf-8'),
 3:'c'.encode('utf-8'),
 4:'d'.encode('utf-8'),
 5:'e'.encode('utf-8'),
 6:'f'.encode('utf-8'),
 7:'g'.encode('utf-8'),
 8:'h'.encode('utf-8'),
 9:'i'.encode('utf-8'),
 10:'j'.encode('utf-8'),
 -1:'k'.encode('utf-8'),
 -2:'l'.encode('utf-8'),
 -3:'m'.encode('utf-8'),
 -4:'n'.encode('utf-8'),
 -5:'o'.encode('utf-8'),
 -6:'p'.encode('utf-8'),
 -7:'q'.encode('utf-8'),
 -8:'r'.encode('utf-8'),
 -9:'s'.encode('utf-8'),
 -10:'t'.encode('utf-8'),
 }

 commandDictUpper= {
 1:'A'.encode('utf-8'),
 2:'B'.encode('utf-8'),
 3:'C'.encode('utf-8'),
 4:'D'.encode('utf-8'),
 5:'E'.encode('utf-8'),
 6:'F'.encode('utf-8'),
 7:'G'.encode('utf-8'),
 8:'H'.encode('utf-8'),
 9:'I'.encode('utf-8'),
 10:'J'.encode('utf-8'),
 -1:'K'.encode('utf-8'),
 -2:'L'.encode('utf-8'),
 -3:'M'.encode('utf-8'),
 -4:'M'.encode('utf-8'),
 -5:'O'.encode('utf-8'),
 -6:'P'.encode('utf-8'),
 -7:'Q'.encode('utf-8'),
 -8:'R'.encode('utf-8'),
 -9:'S'.encode('utf-8'),
 -10:'T'.encode('utf-8'),
 }